name: Lint

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:

    lint:
      runs-on: ubuntu-latest

      steps:
      - name: check out github repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: init
        run: npm install
      
      - name: fmt
        run: npm run style-check

      - name: lint
        run: npm run solhint

      - name: Spell Check
        run: npx cspell "./**/**/**.sol" && npx cspell "./**/**/**.ts"
