name: Test

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:

    solidity:
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: install dapp.tools
        run: curl https://dapp.tools/install | sh
      
      - name: install solc 0.8.0
        run: nix-env -f https://github.com/dapphub/dapptools/archive/master.tar.gz -iA solc-static-versions.solc_0_8_0

      - name: init
        run: export PATH=/home/runner/.nix-profile/bin/:$PATH && dapp update

      - name: test
        run: export PATH=/home/runner/.nix-profile/bin/:$PATH && make dapp-test
