name: Tests

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
    unit:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Install dependencies
          run: npm install
        - name: compile
          run: npx hardhat compile
        - name: test
          run: npm run test
    sim:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Install dependencies
          run: npm install
        - name: simulation
          run: npm run sim




