name: Test

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:

    solidity:
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v11
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: install dapp.tools
        run: curl https://dapp.tools/install | sh

      - name: init
        run: export PATH=/home/runner/.nix-profile/bin/:$PATH && dapp update

      - name: test
        run: export PATH=/home/runner/.nix-profile/bin/:$PATH && make test
