name: Tests

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
    unit:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Install dependencies
          run: npm ci && npm run load-contracts
        - name: compile
          run: npx hardhat compile
        - name: test
          run: npm run test
    sim:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Install dependencies
          run: pip3 install numpy && npm ci && npm run load-contracts
        - name: compile
          run: npx hardhat compile
        - name: simulation
          run: npm run sim
    typecheck:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Install dependencies
          run: npm ci && npm run load-contracts
        - name: compile
          run: npx hardhat compile
        - name: typecheck
          run: npm run typecheck
